import React, { useState } from 'react';
import { Layers, ShieldAlert, Sparkles, RotateCw, ArrowRight } from 'lucide-react';
import { KaTeXMath } from '../common/KaTeXMath';

interface Piece {
  id: number;
  name: string;
  color: string;
  groupElement: string;
  description: string;
}

const PIECES: Piece[] = [
  { id: 1, name: 'Core Set M', color: '#06b6d4', groupElement: '1', description: 'Points fixed or associated with the identity rotation.' },
  { id: 2, name: 'Orbit Piece A', color: '#8b5cf6', groupElement: 'a', description: 'Points generated by words starting with rotation a.' },
  { id: 3, name: 'Orbit Piece A⁻¹', color: '#ec4899', groupElement: 'a⁻¹', description: 'Points generated by words starting with inverse rotation a⁻¹.' },
  { id: 4, name: 'Orbit Piece B', color: '#f59e0b', groupElement: 'b', description: 'Points generated by words starting with rotation b.' },
  { id: 5, name: 'Orbit Piece B⁻¹', color: '#10b981', groupElement: 'b⁻¹', description: 'Points generated by words starting with inverse rotation b⁻¹.' }
];

export const BanachTarskiLab: React.FC = () => {
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1);
  const [selectedPiece, setSelectedPiece] = useState<Piece | null>(null);

  return (
    <div className="flex flex-col gap-6 p-6 rounded-2xl bg-slate-900/60 border border-slate-800 text-slate-200">
      {/* Warning Alert against physical cutting misconceptions */}
      <div className="p-4 rounded-xl bg-amber-950/30 border border-amber-500/30 text-xs text-amber-200 flex items-start gap-3">
        <ShieldAlert className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div>
          <strong className="text-amber-300 font-bold block mb-1">
            Crucial Conceptual Clarification: Not a Physical Carving Method
          </strong>
          The Banach–Tarski paradox is a pure theorem of set theory under the Axiom of Choice. The 5 pieces are not physical knife-cut chunks; they are infinitely dense, non-measurable point clouds that do not possess a well-defined Lebesgue volume in real physical matter.
        </div>
      </div>

      {/* Step Navigator */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <div className="flex items-center gap-2">
          {[1, 2, 3, 4].map((s) => (
            <button
              key={s}
              type="button"
              onClick={() => setStep(s as any)}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-mono font-bold transition-all ${
                step === s
                  ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/20'
                  : 'bg-slate-950 text-slate-400 hover:text-slate-200 border border-slate-800'
              }`}
            >
              Step {s}
            </button>
          ))}
        </div>

        <span className="text-xs font-mono text-slate-400">
          {step === 1 && '1. Unit Solid Sphere'}
          {step === 2 && '2. Axiom of Choice Partition'}
          {step === 3 && '3. Rigid SO(3) Rotations'}
          {step === 4 && '4. Two Identical Spheres'}
        </span>
      </div>

      {/* Interactive Stage Display */}
      <div className="relative h-64 rounded-2xl bg-gradient-to-b from-slate-950 to-slate-900 border border-slate-800 flex items-center justify-center p-6 overflow-hidden">
        {step === 1 && (
          <div className="flex flex-col items-center gap-3 text-center">
            <div className="w-32 h-32 rounded-full bg-gradient-to-tr from-cyan-600 to-blue-400 shadow-[0_0_40px_rgba(6,182,212,0.3)] animate-pulse flex items-center justify-center text-slate-950 font-bold text-sm">
              Volume = 1
            </div>
            <p className="text-xs text-slate-400">Start with a single solid unit ball in <KaTeXMath math="\mathbb{R}^3" />.</p>
          </div>
        )}

        {step === 2 && (
          <div className="flex flex-col items-center gap-4 text-center">
            <div className="flex items-center gap-3">
              {PIECES.map((piece) => (
                <button
                  key={piece.id}
                  type="button"
                  onClick={() => setSelectedPiece(piece)}
                  style={{ backgroundColor: `${piece.color}25`, borderColor: piece.color }}
                  className="w-14 h-14 rounded-2xl border-2 flex flex-col items-center justify-center transition-transform hover:scale-110"
                >
                  <span className="text-[10px] font-mono font-bold" style={{ color: piece.color }}>{piece.groupElement}</span>
                  <span className="text-[8px] text-slate-400">Piece {piece.id}</span>
                </button>
              ))}
            </div>
            <p className="text-xs text-slate-300">
              The ball is partitioned into 5 non-measurable pieces using orbits of the Free Group <KaTeXMath math="F_2" /> in <KaTeXMath math="SO(3)" />.
            </p>
          </div>
        )}

        {step === 3 && (
          <div className="flex items-center justify-center gap-8 text-center">
            <div className="flex flex-col items-center gap-2">
              <div className="w-20 h-20 rounded-full border-2 border-dashed border-cyan-400/60 flex items-center justify-center animate-spin">
                <RotateCw className="w-8 h-8 text-cyan-400" />
              </div>
              <span className="text-xs font-mono text-cyan-300">Rotate Piece A by a⁻¹</span>
            </div>
            <ArrowRight className="w-6 h-6 text-slate-600" />
            <div className="flex flex-col items-center gap-2">
              <div className="w-20 h-20 rounded-full border-2 border-dashed border-purple-400/60 flex items-center justify-center animate-spin">
                <RotateCw className="w-8 h-8 text-purple-400" />
              </div>
              <span className="text-xs font-mono text-purple-300">Rotate Piece B by b⁻¹</span>
            </div>
          </div>
        )}

        {step === 4 && (
          <div className="flex items-center justify-center gap-12 text-center">
            <div className="flex flex-col items-center gap-2">
              <div className="w-24 h-24 rounded-full bg-gradient-to-tr from-cyan-600 to-blue-500 shadow-[0_0_25px_rgba(6,182,212,0.3)] flex items-center justify-center text-slate-950 font-bold text-xs">
                Ball 1 (Vol = 1)
              </div>
              <span className="text-[11px] text-cyan-300 font-mono">From pieces (1, 2, 3)</span>
            </div>

            <span className="text-2xl font-bold text-amber-400">+</span>

            <div className="flex flex-col items-center gap-2">
              <div className="w-24 h-24 rounded-full bg-gradient-to-tr from-purple-600 to-pink-500 shadow-[0_0_25px_rgba(168,85,247,0.3)] flex items-center justify-center text-slate-950 font-bold text-xs">
                Ball 2 (Vol = 1)
              </div>
              <span className="text-[11px] text-purple-300 font-mono">From pieces (4, 5)</span>
            </div>
          </div>
        )}
      </div>

      {/* Selected Piece Details */}
      {selectedPiece && (
        <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs">
          <strong className="text-slate-100">{selectedPiece.name}: </strong>
          <span className="text-slate-300">{selectedPiece.description}</span>
        </div>
      )}

      {/* Mathematical Mechanism */}
      <div className="p-4 rounded-xl bg-slate-950/50 border border-slate-800 text-xs text-slate-300 leading-relaxed">
        <h4 className="font-bold text-slate-200 mb-1">How is this mathematically possible?</h4>
        <p className="mb-2">
          The rotation group <KaTeXMath math="SO(3)" /> contains a free subgroup on two generators <KaTeXMath math="F_2 = \langle a, b \rangle" />. By the Axiom of Choice, we choose one point from each orbit. The paradox emerges because non-measurable sets cannot be assigned a volume, so the principle of volume conservation does not apply to them!
        </p>
      </div>
    </div>
  );
};
