import { Category, Problem, MathematicalWonder, TimelineEvent, Visualization } from '../types/math';

export const FALLBACK_CATEGORIES: Category[] = [
  { id: 1, slug: 'number-theory', name: 'Number Theory', description: 'The arithmetic of integers, primes, and divisibility.', icon: 'Binary', color: '#3b82f6', displayOrder: 1 },
  { id: 2, slug: 'topology', name: 'Topology', description: 'Properties of space preserved under continuous deformation.', icon: 'Shapes', color: '#8b5cf6', displayOrder: 2 },
  { id: 3, slug: 'geometry', name: 'Geometry', description: 'Shapes, curvature, manifolds, and spatial relationships.', icon: 'Compass', color: '#06b6d4', displayOrder: 3 },
  { id: 4, slug: 'logic-foundations', name: 'Mathematical Logic & Foundations', description: 'Formal proof systems, computability, and independence.', icon: 'Cpu', color: '#ec4899', displayOrder: 4 },
  { id: 5, slug: 'computer-science', name: 'Theoretical Computer Science', description: 'Complexity classes, algorithmic limits, and automata.', icon: 'Terminal', color: '#10b981', displayOrder: 5 },
  { id: 6, slug: 'mathematical-physics', name: 'Mathematical Physics', description: 'Fluid dynamics, quantum fields, and spacetime geometry.', icon: 'Atom', color: '#f59e0b', displayOrder: 6 },
  { id: 7, slug: 'analysis', name: 'Mathematical Analysis', description: 'Limits, differential equations, and complex analysis.', icon: 'TrendingUp', color: '#6366f1', displayOrder: 7 },
  { id: 8, slug: 'paradoxes', name: 'Paradoxes & Mathematical Phenomena', description: 'Mind-bending theorems, counter-intuitive results, and fractal sets.', icon: 'Sparkles', color: '#e11d48', displayOrder: 8 }
];

export const FALLBACK_PROBLEMS: Problem[] = [
  {
    id: 1,
    slug: 'riemann-hypothesis',
    title: 'Riemann Hypothesis',
    shortDescription: 'All non-trivial zeros of the Riemann zeta function have a real part equal to 1/2.',
    fullDescription: 'Proposed by Bernhard Riemann in 1859, the Riemann Hypothesis connects the distribution of prime numbers to the complex zeros of the analytic continuation of the zeta function. It remains the most celebrated open problem in pure mathematics.',
    field: 'Analytic Number Theory',
    categoryId: 1,
    status: 'OPEN',
    difficulty: 'Extreme',
    yearIntroduced: 1859,
    lastVerified: '2026-03-01',
    statusSource: 'Clay Mathematics Institute / Annals of Mathematics',
    sourceType: 'Official Millennium Prize Problem',
    statusNotes: 'Clay Millennium Problem. Verified for the first 10^13 zeros numerically, but computational evidence does not constitute a mathematical proof.',
    mathematicalStatement: '\\zeta(s) = \\sum_{n=1}^{\\infty} \\frac{1}{n^s} = \\prod_{p \\text{ prime}} \\frac{1}{1 - p^{-s}}, \\quad \\Re(s) = \\frac{1}{2}',
    intuition: 'Primes look randomly scattered, but the zeta function acts like a musical harmonic spectrum for primes. The Riemann Hypothesis claims that the mathematical "frequencies" controlling the distribution of primes are completely pure and centered on a single critical line.',
    whyItMatters: 'A proof would yield the sharpest possible bounds for the Prime Number Theorem error term, establish hundreds of conditional theorems in number theory, and confirm deep connections between quantum chaos and complex analysis.',
    whatWeKnow: [
      'The functional equation establishes symmetry around Re(s) = 1/2.',
      'At least 41% of non-trivial zeros lie precisely on the critical line.',
      'Over 10 trillion non-trivial zeros have been checked by computers, and all lie on the critical line.'
    ],
    whatWeDontKnow: [
      'Whether a single non-trivial zero lies off the critical line.',
      'Whether all zeros are simple (multiplicity 1).'
    ],
    partialResults: [
      'Hardy (1914): Infinitely many zeros lie on the critical line.',
      'Levinson (1974): At least 34.7% of zeros are on the line.',
      'Conrey (1989): More than 40.77% are on the line.'
    ],
    commonMisconceptions: [
      'Checking billions of zeros by computer proves the hypothesis. (False: In number theory, counterexamples can appear at unimaginably high values, e.g. Skewes number).',
      'The trivial zeros are on the critical line. (False: They are real negative integers s = -2, -4, -6...).'
    ],
    history: "Formulated in Riemann's landmark 1859 paper 'On the Number of Primes Less Than a Given Magnitude'. Selected by David Hilbert as Problem 8 in 1900 and as a Millennium Prize Problem in 2000.",
    visualizationSlug: 'riemann-hypothesis',
    hasExperiment: true,
    experimentSlug: 'riemann-hypothesis',
    relatedProblems: ['twin-prime-conjecture', 'goldbach-conjecture'],
    sourceIds: [1, 2],
    tags: ['Millennium Problem', 'Primes', 'Zeta Function', 'Complex Analysis'],
    claimedSolutions: ['Atiyah (2018): Claimed proof via Todd polynomials; consensus concluded it contained fundamental gaps.'],
    historicalStatuses: ['1859: Conjectured by Bernhard Riemann', '1900: Hilbert 8th Problem', '2000: Clay Millennium Prize Problem ($1,000,000)']
  },
  {
    id: 2,
    slug: 'p-vs-np',
    title: 'P vs NP Problem',
    shortDescription: 'Can every problem whose solution can be quickly verified also be quickly solved?',
    fullDescription: 'Formulated by Stephen Cook (1971) and Leonid Levin (1973), P vs NP asks whether computational decision problems that can be verified in polynomial time can also be solved by an algorithm running in polynomial time.',
    field: 'Theoretical Computer Science',
    categoryId: 5,
    status: 'OPEN',
    difficulty: 'Extreme',
    yearIntroduced: 1971,
    lastVerified: '2026-02-15',
    statusSource: 'Clay Mathematics Institute',
    sourceType: 'Official Millennium Prize Problem',
    statusNotes: 'Wide consensus among complexity theorists suspects P != NP, but neither a separation nor a collapse has been proven.',
    mathematicalStatement: '\\text{P} = \\bigcup_{k \\ge 1} \\text{DTIME}(n^k) \\quad \\stackrel{?}{=} \\quad \\text{NP} = \\bigcup_{k \\ge 1} \\text{NTIME}(n^k)',
    intuition: 'Finding a needle in a haystack is difficult, but checking whether a shiny object is indeed the needle is effortless. Does every problem with easy verification admit an equally easy search method?',
    whyItMatters: 'If P = NP, modern cryptography collapses, algorithmic optimization solves protein folding instantaneously, and mathematical discovery could be automated.',
    whatWeKnow: [
      'Hundreds of vital problems (Traveling Salesperson, Boolean SAT, Knapsack) are NP-complete.',
      'Relativization, natural proofs, and algebrization barriers prove standard proof techniques cannot resolve P vs NP.'
    ],
    whatWeDontKnow: ['Whether P equals NP.', 'Whether NP-complete problems require exponential time.'],
    partialResults: ['Cook-Levin Theorem: SAT is NP-complete.'],
    commonMisconceptions: [
      'NP stands for Non-Polynomial. (False: It stands for Nondeterministic Polynomial time).',
      'Quantum computers solve all NP-complete problems in polynomial time. (False: NP is not believed to be contained in BQP).'
    ],
    history: 'Introduced independently by Stephen Cook (1971) and Leonid Levin (1973).',
    visualizationSlug: 'p-vs-np',
    hasExperiment: false,
    relatedProblems: ['halting-problem'],
    sourceIds: [1],
    tags: ['Millennium Problem', 'Algorithms', 'Complexity Theory'],
    claimedSolutions: [],
    historicalStatuses: ['1971: Cook formulated NP-completeness', '2000: Clay Millennium Prize Problem']
  },
  {
    id: 3,
    slug: 'poincare-conjecture',
    title: 'Poincaré Conjecture',
    shortDescription: 'Every simply connected, closed 3-dimensional manifold is homeomorphic to the 3-sphere.',
    fullDescription: 'Posed by Henri Poincaré in 1904, the conjecture asserts that the only compact 3-manifold without boundary where every closed loop can be shrunk to a point is the 3-sphere.',
    field: 'Differential Geometry & Topology',
    categoryId: 2,
    status: 'SOLVED',
    difficulty: 'Extreme',
    yearIntroduced: 1904,
    lastVerified: '2026-01-10',
    statusSource: 'Clay Mathematics Institute / Annals of Mathematics',
    sourceType: 'Verified Clay Millennium Solution',
    statusNotes: 'SOLVED by Grigori Perelman in 2002–2003 utilizing Richard Hamilton\'s Ricci flow with surgery.',
    mathematicalStatement: '\\text{Let } M \\text{ be a compact 3-manifold without boundary. If } \\pi_1(M) = 0, \\text{ then } M \\cong S^3.',
    intuition: 'If you tie a rubber band around an apple, you can shrink it to a point without leaving the surface. On a doughnut, loops wrap through the hole and get stuck. Poincaré asked: is the 3-sphere the only 3D universe where all loops shrink?',
    whyItMatters: 'Completed the classification of 3-manifolds and proved Thurston\'s Geometrization Conjecture.',
    whatWeKnow: ['Fully proved in all dimensions: n >= 5 (Smale, 1961), n = 4 (Freedman, 1982), n = 3 (Perelman, 2003).'],
    whatWeDontKnow: ['The smooth 4D Poincaré conjecture remains an active frontier.'],
    partialResults: ['Hamilton (1982): Introduced Ricci flow.', 'Perelman (2002): Solved finite-time singularities with surgery.'],
    commonMisconceptions: ['Dimension 3 was the easiest case. (False: Dimensions 3 and 4 were mathematically the most difficult).'],
    history: 'Posed in 1904 by Poincaré; solved in 2002 by Grigori Perelman who famously declined the $1M prize.',
    visualizationSlug: 'poincare-conjecture',
    hasExperiment: false,
    relatedProblems: ['hodge-conjecture'],
    sourceIds: [1, 3],
    tags: ['Solved', 'Topology', 'Ricci Flow', 'Millennium Problem'],
    claimedSolutions: ['Perelman\'s proof accepted in 2006.'],
    historicalStatuses: ['1904: Conjectured', '2000: Millennium Prize Problem', '2003: Proved by Perelman']
  },
  {
    id: 4,
    slug: 'navier-stokes-smoothness',
    title: 'Navier–Stokes Existence and Smoothness',
    shortDescription: 'Do smooth, physically reasonable solutions always exist for the 3D incompressible Navier-Stokes equations?',
    fullDescription: 'The Navier-Stokes equations govern the motion of viscous fluids (water, air). The open mathematical challenge is to prove whether solutions starting from smooth initial data remain smooth for all time or can develop finite-time singularities (blow-up).',
    field: 'Mathematical Physics & PDE',
    categoryId: 6,
    status: 'OPEN',
    difficulty: 'Extreme',
    yearIntroduced: 1845,
    lastVerified: '2026-03-05',
    statusSource: 'Clay Mathematics Institute',
    sourceType: 'Official Millennium Prize Problem',
    statusNotes: 'Official status is OPEN. Periodic claims of blow-up or global regularity appear in literature but either contain errors or apply to modified equations.',
    mathematicalStatement: '\\frac{\\partial \\mathbf{u}}{\\partial t} + (\\mathbf{u} \\cdot \\nabla)\\mathbf{u} = -\\frac{1}{\\rho}\\nabla p + \\nu \\nabla^2 \\mathbf{u} + \\mathbf{f}, \\quad \\nabla \\cdot \\mathbf{u} = 0',
    intuition: 'When water flows, it can form violent eddies and turbulence. Does fluid velocity or vorticity ever concentrate to infinity at a single point in finite time, or does viscosity always keep the fluid smooth?',
    whyItMatters: 'Understanding fluid turbulence is essential for aerodynamics, climate modeling, and theoretical physics. A breakdown in smoothness would indicate classical fluid mechanics is mathematically incomplete.',
    whatWeKnow: [
      'Global smooth solutions exist in 2 dimensions (Leray, 1934).',
      'Weak solutions exist globally in 3 dimensions (Leray-Hopf weak solutions), but their uniqueness and smoothness remain unproven.',
      'If a singularity forms, the vorticity must blow up sufficiently fast (Beale-Kato-Majda criterion).'
    ],
    whatWeDontKnow: ['Whether a smooth 3D flow can blow up in finite time from smooth initial conditions of finite energy.'],
    partialResults: [
      'Caffarelli-Kohn-Nirenberg (1982): Singular set in space-time has 1D Hausdorff measure zero.',
      'Tao (2016): Finite-time blow-up exists for an averaged version of Navier-Stokes.'
    ],
    commonMisconceptions: ['Computer simulations showing turbulence prove singularities exist. (False: Numerical grids have finite resolution and cannot distinguish between high peaks and true infinite blow-up).'],
    history: 'Formulated by Claude-Louis Navier (1822) and George Gabriel Stokes (1845). Included among the Clay Millennium Problems in 2000.',
    visualizationSlug: 'navier-stokes',
    hasExperiment: false,
    relatedProblems: ['yang-mills-mass-gap'],
    sourceIds: [1],
    tags: ['Millennium Problem', 'Fluids', 'PDE', 'Turbulence'],
    claimedSolutions: [
      'Mukhtarbay Otelbaev (2014) claimed proof of regularity; counterexample found.',
      'Thomas Hou et al. (2022) demonstrated singularity for 3D Euler with boundary, but Navier-Stokes remains open.'
    ],
    historicalStatuses: ['1845: Formulated by Stokes', '2000: Clay Millennium Prize Problem', 'Status requires verification: Ongoing active research']
  },
  {
    id: 5,
    slug: 'collatz-conjecture',
    title: 'Collatz Conjecture (3n + 1)',
    shortDescription: 'Does the iterative map n/2 (even) or 3n+1 (odd) always reach the cycle 4 -> 2 -> 1 for every positive integer?',
    fullDescription: 'Named after Lothar Collatz (1937), the conjecture posits that repeating the simple arithmetic rule f(n) = n/2 if n is even, and f(n) = 3n + 1 if n is odd, always eventually arrives at 1.',
    field: 'Dynamical Systems & Number Theory',
    categoryId: 1,
    status: 'OPEN',
    difficulty: 'Intermediate',
    yearIntroduced: 1937,
    lastVerified: '2026-03-01',
    statusSource: 'Annals of Mathematics / Tao (2022)',
    sourceType: 'Peer-Reviewed Research Literature',
    statusNotes: 'OPEN. Paul Erdős remarked: "Mathematics may not yet be ready for such problems." Verified up to 2^68.',
    mathematicalStatement: 'T(n) = \\begin{cases} \\frac{n}{2}, & \\text{if } n \\text{ is even} \\\\ 3n + 1, & \\text{if } n \\text{ is odd} \\end{cases} \\quad \\forall n \\in \\mathbb{Z}^+, \\exists k : T^{(k)}(n) = 1.',
    intuition: 'Odd steps push numbers upward, but adding 1 creates an even number, ensuring at least one division by 2. On average geometric descent wins, but proving every single integer trajectory terminates is extraordinarily challenging.',
    whyItMatters: 'Demonstrates how simplest elementary arithmetic rules can harbor pseudo-random complexity and potential undecidability.',
    whatWeKnow: [
      'Verified computationally for all start values up to ~2.95 * 10^20.',
      'Terence Tao (2019/2022): Almost all Collatz orbits attain almost arbitrarily small values.'
    ],
    whatWeDontKnow: ['Whether a number exists that escapes to infinity.', 'Whether any other cycle exists.'],
    partialResults: ['Eliahou (1993): Any other non-trivial cycle must have period > 17 billion.'],
    commonMisconceptions: ['Verifying up to 2^68 means it is mathematically certain. (False: Computational testing is not proof).'],
    history: 'Circulated by Collatz, Ulam, and Kakutani in the 1930s-1950s.',
    visualizationSlug: 'collatz-conjecture',
    hasExperiment: true,
    experimentSlug: 'collatz-lab',
    relatedProblems: ['goldbach-conjecture', 'halting-problem'],
    sourceIds: [7],
    tags: ['Number Theory', 'Dynamical Systems', 'Interactive Lab'],
    claimedSolutions: [],
    historicalStatuses: ['1937: Proposed by Lothar Collatz', '2019: Terence Tao proves almost all orbits reach small values']
  },
  {
    id: 6,
    slug: 'goldbach-conjecture',
    title: 'Goldbach Conjecture',
    shortDescription: 'Every even integer greater than 2 can be expressed as the sum of two primes.',
    fullDescription: 'Proposed by Christian Goldbach in 1742, this is one of the oldest and most celebrated open conjectures in number theory.',
    field: 'Additive Number Theory',
    categoryId: 1,
    status: 'OPEN',
    difficulty: 'Advanced',
    yearIntroduced: 1742,
    lastVerified: '2026-02-28',
    statusSource: 'Academic Consensus',
    sourceType: 'Historical Open Conjecture',
    statusNotes: 'OPEN. Weak Goldbach proved by Helfgott (2013). Strong Goldbach remains open.',
    mathematicalStatement: '\\forall n \\in 2\\mathbb{N}, n > 2 \\implies \\exists p, q \\in \\mathbb{P} : n = p + q.',
    intuition: 'As even numbers grow, primes become more abundant below them, giving more combinations to sum to n. Yet proving no single even number is skipped is an open challenge.',
    whyItMatters: 'Unlocks the relationship between addition and the multiplicative nature of prime numbers.',
    whatWeKnow: ['Verified computationally up to 4 * 10^18.', 'Weak Goldbach (odd n > 5 is sum of 3 primes) proved by Harald Helfgott in 2013.'],
    whatWeDontKnow: ['Whether an even integer exists that is not the sum of two primes.'],
    partialResults: ['Chen (1973): Every large even integer is p + (prime or product of two primes).'],
    commonMisconceptions: ['Proving weak Goldbach immediately implies strong Goldbach. (False).'],
    history: 'Goldbach letter to Euler in 1742.',
    visualizationSlug: 'goldbach-conjecture',
    hasExperiment: true,
    experimentSlug: 'goldbach-lab',
    relatedProblems: ['twin-prime-conjecture', 'riemann-hypothesis'],
    sourceIds: [4],
    tags: ['Number Theory', 'Primes', 'Interactive Lab'],
    claimedSolutions: [],
    historicalStatuses: ['1742: Stated by Goldbach', '2013: Weak Goldbach proved']
  },
  {
    id: 7,
    slug: 'twin-prime-conjecture',
    title: 'Twin Prime Conjecture',
    shortDescription: 'Are there infinitely many pairs of prime numbers that differ by exactly 2?',
    fullDescription: 'The conjecture asserts that the gap between consecutive primes equals 2 infinitely often: (3,5), (5,7), (11,13), (17,19)...',
    field: 'Analytic Number Theory',
    categoryId: 1,
    status: 'OPEN',
    difficulty: 'Advanced',
    yearIntroduced: 1846,
    lastVerified: '2026-03-01',
    statusSource: 'Annals of Mathematics / Polymath8',
    sourceType: 'Peer-Reviewed Literature',
    statusNotes: 'OPEN. Bounded gaps between primes proven to be <= 246 unconditionally.',
    mathematicalStatement: '\\liminf_{n \\to \\infty} (p_{n+1} - p_n) = 2',
    intuition: 'As numbers grow large, primes thin out. Do twin primes eventually disappear, or do pairs separated by 2 continue forever?',
    whyItMatters: 'Reveals the fundamental fine-grained distribution of prime gaps.',
    whatWeKnow: ['Infinitely many prime pairs exist with gap <= 246 (Zhang, Maynard, Polymath8).'],
    whatWeDontKnow: ['Whether the bound can be reduced unconditionally to 2.'],
    partialResults: ['Zhang (2013): First finite bound < 70,000,000.', 'Maynard & Polymath8 (2014): Bound reduced to 246.'],
    commonMisconceptions: ['Twin primes stop appearing for gigantic numbers. (False: The largest known twin prime pair has over 388,000 digits).'],
    history: 'Formulated in 1846 by Alphonse de Polignac.',
    visualizationSlug: 'twin-prime-conjecture',
    hasExperiment: true,
    experimentSlug: 'twin-prime-lab',
    relatedProblems: ['goldbach-conjecture', 'riemann-hypothesis'],
    sourceIds: [4],
    tags: ['Number Theory', 'Primes', 'Interactive Lab'],
    claimedSolutions: [],
    historicalStatuses: ['1846: Posed by Polignac', '2013: Zhang proves bounded gaps', '2014: Bound reduced to 246']
  },
  {
    id: 8,
    slug: 'halting-problem',
    title: 'The Halting Problem',
    shortDescription: 'Can a general algorithm determine whether an arbitrary computer program will ever finish running?',
    fullDescription: 'Alan Turing proved in 1936 that it is logically impossible for any algorithm to determine, for all possible program-input pairs, whether the program halts or runs forever.',
    field: 'Mathematical Logic & Computability',
    categoryId: 4,
    status: 'UNDECIDABLE',
    difficulty: 'Advanced',
    yearIntroduced: 1936,
    lastVerified: '2026-01-01',
    statusSource: 'Turing (1936)',
    sourceType: 'Proven Undecidable Theorem',
    statusNotes: 'PROVEN UNDECIDABLE. This is not an unsolved problem; it is a mathematical proof that no such algorithm can exist.',
    mathematicalStatement: 'H = \\{ \\langle M, w \\rangle \\mid M \\text{ halts on } w \\} \\notin \\mathbf{R}',
    intuition: 'If a master checker "WillHalt(P)" existed, we could construct a paradox program "Opposite(P)" that inverts the verdict. If WillHalt says Opposite halts, Opposite loops; if it says it loops, Opposite halts. Contradiction!',
    whyItMatters: 'Defines the absolute boundaries of mechanical computation and formal verification.',
    whatWeKnow: ['Undecidable for Turing machines and all equivalent computational models.'],
    whatWeDontKnow: ['Not applicable; fully resolved.'],
    partialResults: ['Turing (1936): Diagonalization proof.'],
    commonMisconceptions: ['Computers can never tell if ANY program halts. (False: Many specific programs are easily verified; no single algorithm handles ALL programs).'],
    history: 'Published by Alan Turing in 1936 resolving Hilbert\'s Entscheidungsproblem.',
    visualizationSlug: 'halting-problem',
    hasExperiment: false,
    relatedProblems: ['continuum-hypothesis', 'p-vs-np'],
    sourceIds: [5],
    tags: ['Undecidable', 'Turing Machine', 'Logic'],
    claimedSolutions: [],
    historicalStatuses: ['1936: Proved undecidable by Alan Turing']
  },
  {
    id: 9,
    slug: 'continuum-hypothesis',
    title: 'The Continuum Hypothesis',
    shortDescription: 'Is there a set whose size is strictly between that of the integers and the real numbers?',
    fullDescription: 'Posed by Georg Cantor in 1878, the Continuum Hypothesis states that there is no set whose cardinality is strictly between that of the integers and the real numbers: 2^aleph_0 = aleph_1.',
    field: 'Set Theory & Foundations',
    categoryId: 4,
    status: 'INDEPENDENT',
    difficulty: 'Extreme',
    yearIntroduced: 1878,
    lastVerified: '2026-01-01',
    statusSource: 'Gödel (1940), Cohen (1963)',
    sourceType: 'Proven Independent of ZFC',
    statusNotes: 'INDEPENDENT of standard ZFC axioms. It cannot be proved or disproved within ZFC.',
    mathematicalStatement: '2^{\\aleph_0} = \\aleph_1 \\iff \\nexists S : |\\mathbb{N}| < |S| < |\\mathbb{R}|',
    intuition: 'Infinity has different sizes. The integers are countably infinite; the reals are uncountably infinite. Cantor asked: is there an intermediate infinity in between?',
    whyItMatters: 'Showed that core mathematical questions can transcend the standard axiomatic foundation.',
    whatWeKnow: ['Gödel (1940): CH cannot be disproved in ZFC.', 'Cohen (1963): CH cannot be proved in ZFC.'],
    whatWeDontKnow: ['Whether a future consensus extension of ZFC will resolve CH.'],
    partialResults: ['Proved independent of ZFC.'],
    commonMisconceptions: ['Independent means we are just waiting for a clever proof. (False: It is mathematically impossible to prove or disprove from ZFC).'],
    history: 'Hilbert\'s 1st Problem in 1900. Resolved by Gödel and Cohen.',
    visualizationSlug: 'continuum-hypothesis',
    hasExperiment: false,
    relatedProblems: ['halting-problem'],
    sourceIds: [6],
    tags: ['Independent', 'Set Theory', 'Logic'],
    claimedSolutions: [],
    historicalStatuses: ['1878: Posed by Cantor', '1940: Gödel consistency', '1963: Cohen independence via forcing']
  },
  {
    id: 10,
    slug: 'birch-swinnerton-dyer',
    title: 'Birch and Swinnerton-Dyer Conjecture',
    shortDescription: 'Relates the number of rational points on an elliptic curve to the behavior of its L-function at s = 1.',
    fullDescription: 'The BSD conjecture asserts that the rank of the abelian group of rational points on an elliptic curve E is equal to the order of the zero of its L-function L(E, s) at s = 1.',
    field: 'Arithmetic Geometry',
    categoryId: 1,
    status: 'OPEN',
    difficulty: 'Extreme',
    yearIntroduced: 1965,
    lastVerified: '2026-01-01',
    statusSource: 'Clay Mathematics Institute',
    sourceType: 'Official Millennium Prize Problem',
    statusNotes: 'Clay Millennium Problem. Proved for rank 0 and rank 1 by Gross-Zagier and Kolyvagin.',
    mathematicalStatement: '\\text{ord}_{s=1} L(E, s) = \\text{rank}(E(\\mathbb{Q}))',
    intuition: 'Elliptic curves are cubic equations y^2 = x^3 + ax + b. Finding rational points on them is notoriously hard. BSD suggests an analytic function (L-function) contains an exact fingerprint of the curve\'s rational geometry.',
    whyItMatters: 'One of the deepest bridges between analysis and arithmetic geometry.',
    whatWeKnow: [
      'Gross-Zagier (1986) and Kolyvagin (1989): Proved BSD when the analytic rank is 0 or 1.',
      'Bhargava-Shankar (2015): A positive proportion of elliptic curves have rank 0 and satisfy BSD.'
    ],
    whatWeDontKnow: ['Whether BSD holds for curves of rank >= 2.'],
    partialResults: ['Proved for curves with complex multiplication (Coates-Wiles, 1977).'],
    commonMisconceptions: ['All elliptic curves have infinitely many rational points. (False: Many have rank 0 and only a finite number of points).'],
    history: 'Formulated in the 1960s via computer experimentation on EDSAC at Cambridge by Bryan Birch and Peter Swinnerton-Dyer.',
    visualizationSlug: 'birch-swinnerton-dyer',
    hasExperiment: false,
    relatedProblems: ['riemann-hypothesis'],
    sourceIds: [1],
    tags: ['Millennium Problem', 'Elliptic Curves', 'L-Functions', 'Arithmetic Geometry'],
    claimedSolutions: [],
    historicalStatuses: ['1965: Conjectured by Birch and Swinnerton-Dyer', '2000: Clay Millennium Prize Problem']
  },
  {
    id: 11,
    slug: 'fermats-last-theorem',
    title: 'Fermat\'s Last Theorem',
    shortDescription: 'No three positive integers a, b, c can satisfy a^n + b^n = c^n for any integer n > 2.',
    fullDescription: 'Conjectured by Pierre de Fermat in 1637 and proved by Andrew Wiles in 1994, resolving a 350-year-old mathematical enigma.',
    field: 'Number Theory & Algebraic Geometry',
    categoryId: 1,
    status: 'SOLVED',
    difficulty: 'Extreme',
    yearIntroduced: 1637,
    lastVerified: '2026-01-01',
    statusSource: 'Annals of Mathematics (Wiles, 1995)',
    sourceType: 'Verified Breakthrough Theorem',
    statusNotes: 'SOLVED by Andrew Wiles with assistance from Richard Taylor in 1994.',
    mathematicalStatement: 'a^n + b^n = c^n \\quad \\text{has no non-trivial integer solutions for } n > 2.',
    intuition: 'For squares (n = 2), integer solutions abound (3^2 + 4^2 = 5^2). Fermat asserted that for cubes and higher powers, integers never balance.',
    whyItMatters: 'Wiles\' proof proved the Modularity Theorem for semistable elliptic curves, transforming modern arithmetic geometry.',
    whatWeKnow: ['Fully proved by Andrew Wiles and Richard Taylor (1995).'],
    whatWeDontKnow: ['Whether Fermat had a valid elementary proof (consensus: no).'],
    partialResults: ['Euler: n = 3.', 'Fermat: n = 4.', 'Kummer: regular primes.'],
    commonMisconceptions: ['Fermat\'s original proof was lost. (False: Modern tools were required).'],
    history: 'Posed in 1637, solved in 1994 by Wiles.',
    visualizationSlug: 'fermats-last-theorem',
    hasExperiment: false,
    relatedProblems: ['beal-conjecture', 'birch-swinnerton-dyer'],
    sourceIds: [8],
    tags: ['Solved', 'Number Theory', 'Elliptic Curves'],
    claimedSolutions: ['Wiles\' proof accepted 1995.'],
    historicalStatuses: ['1637: Conjectured', '1994: Solved by Andrew Wiles']
  },
  {
    id: 12,
    slug: 'hodge-conjecture',
    title: 'Hodge Conjecture',
    shortDescription: 'On projective complex algebraic varieties, Hodge classes are rational linear combinations of algebraic cycles.',
    fullDescription: 'Posed by W. V. D. Hodge in 1950, this Clay Millennium Problem asserts that for projective algebraic varieties, topological information can be completely realized by geometric algebraic subvarieties.',
    field: 'Algebraic Geometry & Complex Geometry',
    categoryId: 3,
    status: 'OPEN',
    difficulty: 'Extreme',
    yearIntroduced: 1950,
    lastVerified: '2026-03-01',
    statusSource: 'Clay Mathematics Institute',
    sourceType: 'Official Millennium Prize Problem',
    statusNotes: 'Clay Millennium Problem. OPEN. Known for dimension <= 3 and for divisors (Lefschetz (1,1)-theorem), but open in general.',
    mathematicalStatement: '\\text{Every Hodge class in } H^{2k}(X, \\mathbb{Q}) \\cap H^{k,k}(X) \\text{ is a rational linear combination of algebraic cycles.}',
    intuition: 'Can the topological shape of an algebraic space always be constructed purely out of geometric algebraic shapes (zero sets of polynomials)?',
    whyItMatters: 'Provides the foundational link between topology, analysis (differential forms), and algebraic geometry.',
    whatWeKnow: [
      'Proved for degree (1,1) classes by the Lefschetz (1,1) theorem.',
      'Proved for varieties of dimension at most 3.',
      'Integral Hodge conjecture is false, rational remains open.'
    ],
    whatWeDontKnow: ['Whether Hodge classes of codimension >= 2 on arbitrary projective varieties are algebraic with rational coefficients.'],
    partialResults: ['Lefschetz (1,1)-theorem: All (1,1) integral classes are algebraic.'],
    commonMisconceptions: ['The conjecture applies with integer coefficients. (False: Rational coefficients are required).'],
    history: 'Formulated by W. V. D. Hodge at the 1950 ICM. Selected as Clay Millennium Problem in 2000.',
    visualizationSlug: undefined,
    hasExperiment: false,
    relatedProblems: ['poincare-conjecture', 'birch-swinnerton-dyer'],
    sourceIds: [1],
    tags: ['Millennium Problem', 'Algebraic Geometry', 'Cohomology'],
    claimedSolutions: [],
    historicalStatuses: ['1950: Conjectured by W. V. D. Hodge', '2000: Clay Millennium Prize Problem']
  },
  {
    id: 13,
    slug: 'yang-mills-mass-gap',
    title: 'Yang–Mills Existence and Mass Gap',
    shortDescription: 'Prove that quantum Yang-Mills theory exists on R^4 and predicts a strictly positive mass gap Delta > 0.',
    fullDescription: 'Formulated by Chen Ning Yang and Robert Mills in 1954, non-abelian gauge theory forms the foundation of the Standard Model of particle physics. The mathematical problem is to provide a rigorous axiomatic quantum field theory and prove that the lightest gauge particle has strictly positive mass.',
    field: 'Quantum Field Theory & Mathematical Physics',
    categoryId: 6,
    status: 'OPEN',
    difficulty: 'Extreme',
    yearIntroduced: 1954,
    lastVerified: '2026-03-01',
    statusSource: 'Clay Mathematics Institute / Jaffe-Witten',
    sourceType: 'Official Millennium Prize Problem',
    statusNotes: 'Clay Millennium Problem. OPEN. Supported by lattice QCD simulations and physical experiments, but no mathematically rigorous proof exists in 4D Minkowski space.',
    mathematicalStatement: '\\exists \\Delta > 0 \\text{ such that every state } \\psi \\text{ orthogonal to the vacuum satisfies } H \\psi \\ge \\Delta \\psi',
    intuition: 'Gluons that carry the strong force are massless in classical physics, yet nuclear forces have a finite range and glueballs have massive weight. Why does a quantum theory of massless particles spontaneously acquire a mass barrier?',
    whyItMatters: 'Explains quark confinement and places relativistic quantum field theory on rigorous mathematical footing.',
    whatWeKnow: [
      'Rigorous constructive quantum field theory exists in 2D and 3D spacetime.',
      'Lattice gauge theory confirms the mass gap numerically to high precision.',
      'Asymptotic freedom proved by Gross, Wilczek, and Politzer.'
    ],
    whatWeDontKnow: ['Rigorous mathematical construction of 4D non-abelian quantum gauge theory and proof of the positive mass gap.'],
    partialResults: ['Constructive field theory successes in lower dimensions.'],
    commonMisconceptions: ['Because physicists use Yang-Mills every day, it is mathematically proven. (False: The continuum limit remains unproven).'],
    history: 'Introduced by Yang and Mills (1954). Jaffe and Witten authored official Clay problem description in 2000.',
    visualizationSlug: undefined,
    hasExperiment: false,
    relatedProblems: ['navier-stokes-smoothness'],
    sourceIds: [1],
    tags: ['Millennium Problem', 'Quantum Physics', 'Gauge Theory', 'Mass Gap'],
    claimedSolutions: [],
    historicalStatuses: ['1954: Formulated by Yang and Mills', '2000: Clay Millennium Prize Problem']
  }
];

export const FALLBACK_WONDERS: MathematicalWonder[] = [
  {
    id: 1,
    slug: 'mobius-strip',
    title: 'Möbius Strip',
    shortDescription: 'A two-dimensional surface with only one side and only one continuous boundary curve.',
    fullDescription: 'Discovered in 1858 by August Ferdinand Möbius and Johann Benedict Listing, the Möbius strip is the quintessential non-orientable surface. Formed by joining a strip\'s ends after a 180° twist.',
    categoryId: 2,
    status: 'PHENOMENON',
    intuition: 'Everyday intuition insists every sheet has two sides (front/back). On a Möbius strip, you can draw a continuous line along the center and visit every part of the surface without crossing an edge.',
    mathematics: 'Non-orientable 2-manifold with boundary. Euler characteristic chi = 0. Parametric: x = (R + v cos(u/2)) cos u, y = (R + v cos(u/2)) sin u, z = v sin(u/2).',
    properties: [
      'One continuous surface (non-orientable)',
      'One continuous edge boundary (homeomorphic to S^1)',
      'Euler characteristic chi = 0',
      'Normal vector flips direction after one complete loop'
    ],
    constructionSteps: [
      '1. Start with a flat rectangular strip.',
      '2. Fix one end in space.',
      '3. Rotate the opposite end gradually by 180 degrees.',
      '4. Join the ends together.',
      '5. The resulting surface is a single continuous side.'
    ],
    parametricEquations: 'x(u, v) = (R + v \\cos(u/2)) \\cos u\ny(u, v) = (R + v \\cos(u/2)) \\sin u\nz(u, v) = v \\sin(u/2)',
    visualizationSlug: 'mobius-strip',
    hasExperiment: true,
    experimentSlug: 'mobius-strip',
    tags: ['Topology', 'Non-orientable', 'Flagship 3D', 'Parametric'],
    sources: ['Möbius, A. F. (1858)', 'Listing, J. B. (1858)']
  },
  {
    id: 2,
    slug: 'klein-bottle',
    title: 'Klein Bottle',
    shortDescription: 'A closed non-orientable surface with no boundary, no inside, and no outside.',
    fullDescription: 'Described in 1882 by Felix Klein, the Klein bottle is a closed two-dimensional surface that cannot be embedded in 3D without self-intersecting, but smoothly embeds in 4D.',
    categoryId: 2,
    status: 'PHENOMENON',
    intuition: 'Imagine sewing two Möbius strips along their single boundaries. You create a closed bottle where a bug crawling on the surface travels from "inside" to "outside" without ever passing through a hole.',
    mathematics: 'Compact connected 2-manifold without boundary. Euler characteristic chi = 0. Fundamental group pi_1 = <a, b | a b a^-1 b = 1>.',
    properties: [
      'Zero boundary components (closed surface)',
      'Non-orientable',
      'Euler characteristic chi = 0',
      'Requires 4 dimensions for non-self-intersecting smooth embedding'
    ],
    constructionSteps: [
      '1. Take a cylinder.',
      '2. Bend one end around.',
      '3. Pass it through the side in 3D immersion.',
      '4. Join with the other end from inside.'
    ],
    parametricEquations: 'Figure-8 immersion: factor = r + cos(u/2)sin v - sin(u/2)sin 2v\nx = factor * cos u\ny = factor * sin u\nz = sin(u/2)sin v + cos(u/2)sin 2v',
    visualizationSlug: 'klein-bottle',
    hasExperiment: true,
    experimentSlug: 'klein-bottle',
    tags: ['Topology', 'Non-orientable', '4D Geometry', 'Interactive 3D'],
    sources: ['Klein, Felix (1882)']
  },
  {
    id: 3,
    slug: 'torus',
    title: 'Parametric Torus',
    shortDescription: 'A doughnut-shaped surface of revolution with genus 1 and rich topological cycles.',
    fullDescription: 'A surface of revolution generated by revolving a circle in three-dimensional space about a coplanar axis. Topologically S^1 x S^1.',
    categoryId: 2,
    status: 'PHENOMENON',
    intuition: 'Unlike a sphere where every loop shrinks to a point, a torus has two fundamentally distinct non-contractible loops: around the hole and around the body.',
    mathematics: 'x = (R + r cos v) cos u, y = (R + r cos v) sin u, z = r sin v. Genus g = 1, chi = 0, pi_1 = Z x Z.',
    properties: [
      'Orientable 2-manifold',
      'Genus g = 1',
      'Euler characteristic chi = 0',
      'Two independent fundamental cycles (meridian & longitude)'
    ],
    constructionSteps: [
      '1. Roll a square into a cylinder.',
      '2. Bend the cylinder into a ring and glue both end circles together.'
    ],
    parametricEquations: 'x = (R + r \\cos v) \\cos u\ny = (R + r \\cos v) \\sin u\nz = r \\sin v',
    visualizationSlug: 'torus',
    hasExperiment: true,
    experimentSlug: 'torus',
    tags: ['Topology', 'Geometry', 'Manifolds', 'Interactive 3D'],
    sources: ['Basic Topology, Springer']
  },
  {
    id: 4,
    slug: 'hilberts-hotel',
    title: 'Hilbert\'s Hotel (Grand Hotel)',
    shortDescription: 'An infinite hotel that is completely full, yet can always accommodate more guests.',
    fullDescription: 'Introduced by David Hilbert in 1924 to illustrate the counterintuitive properties of countably infinite sets (aleph_0).',
    categoryId: 8,
    status: 'PARADOX',
    intuition: 'Even when all infinite rooms are full, moving guest n to n+1 frees up Room 1. Moving guest n to 2n frees up all infinitely many odd rooms!',
    mathematics: 'Demonstrates equinumerosity between N and proper subsets: n -> n+1 and n -> 2n.',
    properties: [
      'Countable infinity aleph_0',
      'Bijection with proper subset',
      'Dedekind-infinite nature'
    ],
    constructionSteps: [
      '1. Hotel is full.',
      '2. Add 1 guest: move n -> n+1. Room 1 opens.',
      '3. Add inf guests: move n -> 2n. Odd rooms open.'
    ],
    parametricEquations: 'n \\mapsto n + k \\quad \\text{or} \\quad n \\mapsto 2n',
    visualizationSlug: 'hilberts-hotel',
    hasExperiment: true,
    experimentSlug: 'hilberts-hotel',
    tags: ['Infinity', 'Paradox', 'Set Theory'],
    sources: ['Hilbert, D. (1924)']
  },
  {
    id: 5,
    slug: 'banach-tarski-paradox',
    title: 'Banach–Tarski Paradox',
    shortDescription: 'A solid ball in 3D can be split into 5 pieces and reassembled into two identical solid balls.',
    fullDescription: 'Proved by Banach and Tarski in 1924, showing that a solid 3D sphere can be partitioned into non-measurable sets and rigidly rearranged into two copies.',
    categoryId: 8,
    status: 'PARADOX',
    intuition: 'This seems physically impossible because physical objects have volume. But Banach-Tarski pieces are infinitely complex non-measurable point clouds that do not have a defined volume.',
    mathematics: 'Relies on the free group on two generators F_2 embedded in SO(3) and the Axiom of Choice.',
    properties: [
      'Requires Axiom of Choice',
      'Pieces are non-measurable',
      'Uses only rigid Euclidean isometries (rotations + translations)'
    ],
    constructionSteps: [
      '1. Embed F_2 in SO(3).',
      '2. Decompose into 4 non-measurable sets.',
      '3. Rotate and reassemble into two spheres.'
    ],
    parametricEquations: 'R_a, R_b \\in SO(3)',
    visualizationSlug: 'banach-tarski',
    hasExperiment: true,
    experimentSlug: 'banach-tarski',
    tags: ['Paradox', 'Axiom of Choice', 'Measure Theory'],
    sources: ['Banach & Tarski (1924)']
  },
  {
    id: 6,
    slug: 'mandelbrot-set',
    title: 'The Mandelbrot Set',
    shortDescription: 'The set of complex numbers c for which z_{n+1} = z_n^2 + c remains bounded starting from 0.',
    fullDescription: 'Visualized by Benoit Mandelbrot in 1980, the benchmark fractal of complex dynamics with infinite self-similarity.',
    categoryId: 8,
    status: 'PHENOMENON',
    intuition: 'A simple quadratic rule repeated infinitely. Depending on escape behavior, infinite ornate patterns and miniature copies of the set blossom at the boundary.',
    mathematics: 'M = {c in C : sup |z_n| < infinity, z_0 = 0, z_{n+1} = z_n^2 + c}. Connected set (Douady-Hubbard).',
    properties: [
      'Connected topological set',
      'Boundary Hausdorff dimension = 2',
      'Contains infinite mini-Mandelbrots'
    ],
    constructionSteps: [
      '1. Pick c = x + iy.',
      '2. Iterate z -> z^2 + c.',
      '3. If |z| > 2, escapes.',
      '4. Color by escape time.'
    ],
    parametricEquations: 'z_{n+1} = z_n^2 + c, \\quad z_0 = 0',
    visualizationSlug: 'mandelbrot-set',
    hasExperiment: true,
    experimentSlug: 'fractal-lab',
    tags: ['Fractals', 'Complex Dynamics', 'Chaos', 'Interactive Lab'],
    sources: ['Mandelbrot (1980)', 'Douady & Hubbard (1982)']
  },
  {
    id: 7,
    slug: 'hyperbolic-geometry',
    title: 'Hyperbolic Geometry',
    shortDescription: 'A non-Euclidean geometry where through a point not on a line, infinitely many parallel lines exist.',
    fullDescription: 'Developed by Lobachevsky, Bolyai, and Gauss, demonstrating that Euclid\'s parallel postulate is not required for a consistent geometry.',
    categoryId: 3,
    status: 'PHENOMENON',
    intuition: 'On a saddle or in hyperbolic space, space expands exponentially. Triangle angles sum to less than 180°, and parallel lines diverge.',
    mathematics: 'Constant negative curvature K = -1. Poincaré disk metric ds = 2|dz| / (1 - |z|^2). Geodesics are circular arcs orthogonal to the boundary circle.',
    properties: [
      'Constant negative curvature',
      'Triangle angles sum to < 180 degrees',
      'Exponential area growth'
    ],
    constructionSteps: [
      '1. Take unit disk in complex plane.',
      '2. Geodesics are circular arcs perpendicular to the boundary.'
    ],
    parametricEquations: 'ds = \\frac{2|dz|}{1 - |z|^2}',
    visualizationSlug: 'hyperbolic-geometry',
    hasExperiment: true,
    experimentSlug: 'hyperbolic-geometry',
    tags: ['Geometry', 'Non-Euclidean', 'Poincaré Disk'],
    sources: ['Lobachevsky (1829)', 'Bolyai (1832)']
  },
  {
    id: 8,
    slug: 'zenos-paradoxes',
    title: "Zeno's Paradoxes",
    shortDescription: 'Ancient philosophical paradoxes questioning the reality of motion, continuous space, and infinite divisibility.',
    fullDescription: 'Devised by Zeno of Elea around 450 BCE to support Parmenides doctrine that all is one and motion is an illusion. The famous paradoxes—Achilles and the Tortoise, the Dichotomy, and the Arrow—challenged human intuition for millennia until calculus and real analysis resolved infinite series convergence.',
    categoryId: 8,
    status: 'PARADOX',
    intuition: 'Achilles can never overtake a tortoise with a head start: before overtaking it, he must reach where it started; by then, the tortoise has moved ahead. An infinite sequence of tasks must be completed in finite time! Calculus answers: an infinite sum of shrinking time intervals converges to a finite number.',
    mathematics: 'Geometric progression: S = a / (1 - r). In the Dichotomy paradox: sum_{n=1}^inf (1/2)^n = 1.',
    properties: [
      'Infinite series convergence',
      'Sum of infinite non-zero intervals can be strictly finite',
      'Geometric progression: S = a / (1 - r)',
      'Calculus resolution of instantaneous velocity via limits: v(t) = ds/dt = lim_{dt -> 0} ds/dt'
    ],
    constructionSteps: [
      '1. Give Tortoise 100m head start.',
      '2. Achilles runs 10x faster than tortoise.',
      '3. When Achilles reaches 100m, Tortoise at 110m.',
      '4. Sum converges: 100 / (1 - 0.1) = 111.11m.',
      '5. Achilles passes Tortoise at t = 11.11 seconds.'
    ],
    parametricEquations: 'x_A(t) = v_A \\cdot t, \\quad x_T(t) = x_0 + v_T \\cdot t',
    visualizationSlug: 'zenos-paradoxes',
    hasExperiment: true,
    experimentSlug: 'zenos-paradoxes',
    tags: ['Infinity', 'Paradox', 'Calculus', 'Series', 'Interactive Lab'],
    sources: ['Aristotle, Physics VI:9', 'Russell, Bertrand (1903)']
  },
  {
    id: 9,
    slug: 'projective-plane',
    title: 'Real Projective Plane (Cross-Cap)',
    shortDescription: 'A non-orientable surface with Euler characteristic 1 that cannot be embedded in 3D without self-intersection.',
    fullDescription: 'The real projective plane RP^2 is the topological space of lines through the origin in R^3. Topologically, it is formed by taking a 2-sphere and identifying antipodal points, or gluing a disk to the boundary of a Möbius strip.',
    categoryId: 2,
    status: 'PHENOMENON',
    intuition: 'Imagine standing in the center of a sphere: every line of sight connects two opposite antipodal points. If you decree that opposite points are actually the exact same location, you get the projective plane.',
    mathematics: 'RP^2 = S^2 / ~ with x ~ -x. Euler characteristic chi = 1, pi_1 = Z_2.',
    properties: [
      'Non-orientable compact 2-manifold without boundary',
      'Euler characteristic chi = 1',
      'Fundamental group pi_1 = Z_2',
      'Non-embeddable in R^3 without self-intersection'
    ],
    constructionSteps: [
      '1. Take northern hemisphere of S^2.',
      '2. Identify opposite boundary points on equator.',
      '3. Sew disk onto boundary of Möbius strip.'
    ],
    parametricEquations: 'x = 0.5 sin(2u) sin^2(v), y = sin(u) cos(2v), z = cos(u) cos(2v)',
    visualizationSlug: 'projective-plane',
    hasExperiment: true,
    experimentSlug: 'projective-plane',
    tags: ['Topology', 'Non-orientable', 'Projective Geometry', 'Interactive 3D'],
    sources: ['Boy, Werner (1901)', 'Hilbert & Cohn-Vossen (1932)']
  },
  {
    id: 10,
    slug: 'cantors-diagonal-argument',
    title: "Cantor's Diagonal Argument",
    shortDescription: 'A proof that the real numbers are strictly more numerous than the integers: uncountability of the continuum.',
    fullDescription: 'Published in 1891 by Georg Cantor, the diagonal argument proved that the set of real numbers is uncountable, establishing that infinity has different magnitudes.',
    categoryId: 4,
    status: 'THEOREM',
    intuition: 'List every real number between 0 and 1. Construct a new number by flipping the n-th digit of the n-th number. This new diagonal number differs from every single number on your list!',
    mathematics: 'For any enumeration f: N -> (0, 1), invert diagonal bits d_n = 1 - f(n)_n. Then d != f(k) for all k. Hence |R| > |N|.',
    properties: [
      'Cardinality |R| = 2^aleph_0 > aleph_0',
      'Constructive refutation of countability',
      'Foundation of Turing halting problem and Gödel incompleteness'
    ],
    constructionSteps: [
      '1. List binary sequences.',
      '2. Invert n-th bit of n-th row.',
      '3. Inverted sequence cannot be on list.'
    ],
    parametricEquations: 'd_n = 1 - s_{n,n}',
    visualizationSlug: 'cantors-diagonal-argument',
    hasExperiment: true,
    experimentSlug: 'cantors-diagonal-argument',
    tags: ['Infinity', 'Set Theory', 'Theorem', 'Cantor', 'Interactive Lab'],
    sources: ['Cantor, Georg (1891)']
  },
  {
    id: 11,
    slug: 'birthday-paradox',
    title: 'The Birthday Paradox',
    shortDescription: 'In a group of only 23 people, there is a greater than 50% probability that at least two share the same birthday.',
    fullDescription: 'A celebrated veridical paradox of probability theory. Despite intuition suggesting you need ~183 people for 50%, only 23 people are required because pairwise comparisons grow quadratically as n(n-1)/2.',
    categoryId: 8,
    status: 'PARADOX',
    intuition: '23 people form 23 * 22 / 2 = 253 pairs. With 253 chances for a match, the collision probability surpasses 50% surprisingly fast.',
    mathematics: 'P(match) = 1 - prod_{k=0}^{n-1} (1 - k/365) approx 1 - e^{-n(n-1)/(2 * 365)}. For n=23, P approx 50.73%.',
    properties: [
      'Combinatorial explosion of pairs',
      'Quadratic pair growth: n(n-1)/2',
      'Foundation of Birthday Attacks in cryptography'
    ],
    constructionSteps: [
      '1. Person 1 has 365/365 available birthdays.',
      '2. Person 2 has 364/365 to avoid collision.',
      '3. Multiply non-collision probabilities.',
      '4. Subtract product from 1.'
    ],
    parametricEquations: 'P(n) = 1 - \\frac{365!}{365^n (365-n)!}',
    visualizationSlug: 'birthday-paradox',
    hasExperiment: true,
    experimentSlug: 'birthday-paradox',
    tags: ['Probability', 'Paradox', 'Combinatorics', 'Cryptography', 'Interactive Lab'],
    sources: ['von Mises, Richard (1939)', 'Feller, William (1968)']
  },
  {
    id: 12,
    slug: 'monty-hall-problem',
    title: 'The Monty Hall Problem',
    shortDescription: 'Switching doors after the host reveals a goat doubles your probability of winning the car from 1/3 to 2/3.',
    fullDescription: 'Based on the television show Let\'s Make a Deal. Contestants choose 1 of 3 doors. The host opens a goat door from the remaining two. Switching doors doubles the winning odds.',
    categoryId: 8,
    status: 'PARADOX',
    intuition: 'Initial pick has 1/3 chance of car, 2/3 chance of goat. If you picked a goat, Monty is forced to open the only other goat, so switching wins the car 100% of the time you picked goat (2/3 overall)!',
    mathematics: 'P(Win | Stay) = 1/3, P(Win | Switch) = 2/3 by Bayes theorem.',
    properties: [
      'Conditional probability & Bayes theorem',
      'Asymmetric information from host action',
      'Frequentist convergence to 66.7% vs 33.3%'
    ],
    constructionSteps: [
      '1. 3 doors: 1 car, 2 goats.',
      '2. Pick door (1/3 car, 2/3 goat).',
      '3. Host opens goat door.',
      '4. Switch door to win 2/3 of games.'
    ],
    parametricEquations: 'P(\\text{Win switch}) = \\frac{N-1}{N}',
    visualizationSlug: 'monty-hall-problem',
    hasExperiment: true,
    experimentSlug: 'monty-hall-problem',
    tags: ['Probability', 'Paradox', 'Bayesian', 'Game Theory', 'Interactive Lab'],
    sources: ['Selvin, Steve (1975)', 'vos Savant, Marilyn (1990)']
  },
  {
    id: 13,
    slug: 'gabriels-horn',
    title: "Gabriel's Horn (Torricelli's Trumpet)",
    shortDescription: 'A geometric surface of revolution with finite volume (pi) but infinite surface area.',
    fullDescription: 'Discovered in 1641 by Evangelista Torricelli. Revolving y = 1/x from x = 1 to infinity produces a trumpet solid with finite volume of pi, yet infinite surface area.',
    categoryId: 7,
    status: 'PARADOX',
    intuition: 'Painter\'s paradox: You could fill the entire trumpet solid with a finite can of paint (pi cubic units), but that same paint could never cover the interior surface area!',
    mathematics: 'V = pi int_1^inf (1/x^2) dx = pi. A = 2 pi int_1^inf (1/x) sqrt(1 + 1/x^4) dx > 2 pi int_1^inf (1/x) dx = infinity.',
    properties: [
      'Finite volume = pi',
      'Infinite surface area',
      'Painter\'s paradox of improper integrals'
    ],
    constructionSteps: [
      '1. Plot curve y = 1/x for x >= 1.',
      '2. Revolve curve 360 degrees around x-axis.',
      '3. Volume converges to pi.',
      '4. Surface area diverges logarithmically.'
    ],
    parametricEquations: 'x = u, y = \\frac{1}{u}\\cos v, z = \\frac{1}{u}\\sin v',
    visualizationSlug: 'gabriels-horn',
    hasExperiment: true,
    experimentSlug: 'gabriels-horn',
    tags: ['Calculus', 'Analysis', 'Paradox', 'Integrals', 'Interactive 3D'],
    sources: ['Torricelli, Evangelista (1644)']
  },
  {
    id: 14,
    slug: 'julia-set',
    title: 'Julia Sets',
    shortDescription: 'Complex fractal boundaries formed by repeating z -> z^2 + c for fixed parameter c.',
    fullDescription: 'Investigated by Gaston Julia and Pierre Fatou in 1918, Julia sets are the dynamical twin of the Mandelbrot set, showing dynamics in the complex z-plane for a constant c.',
    categoryId: 8,
    status: 'PHENOMENON',
    intuition: 'Every point c in the Mandelbrot set yields an entire unique Julia fractal world. If c is inside the Mandelbrot set, the Julia set is connected; otherwise it explodes into dust.',
    mathematics: 'J_c = boundary of bounded orbit set for f_c(z) = z^2 + c.',
    properties: [
      'Connected if and only if c in Mandelbrot set M',
      'Self-similar under backward iterations',
      'Chaotic repeller for complex polynomial dynamics'
    ],
    constructionSteps: [
      '1. Fix complex constant c.',
      '2. For each pixel z, iterate z -> z^2 + c.',
      '3. Color by escape speed.'
    ],
    parametricEquations: 'z_{n+1} = z_n^2 + c',
    visualizationSlug: 'julia-set',
    hasExperiment: true,
    experimentSlug: 'fractal-lab',
    tags: ['Fractals', 'Complex Dynamics', 'Chaos', 'Interactive Lab'],
    sources: ['Julia, Gaston (1918)']
  },
  {
    id: 15,
    slug: 'sierpinski-triangle',
    title: 'Sierpiński Triangle',
    shortDescription: 'A fractal triangle with fractional Hausdorff dimension log(3)/log(2) ~ 1.585 and zero area.',
    fullDescription: 'Introduced by Wacław Sierpiński in 1915, formed by repeatedly removing the central inverted equilateral triangle from each triangular stage.',
    categoryId: 8,
    status: 'PHENOMENON',
    intuition: 'Take a triangle, remove the middle quarter, repeat forever. The leftover shape has zero area yet infinite perimeter and intricate connectivity.',
    mathematics: 'Hausdorff dimension = log 3 / log 2 approx 1.585. Area converges to 0, perimeter diverges to infinity.',
    properties: [
      'Hausdorff dimension ~ 1.585',
      'Zero Lebesgue area',
      'Infinite perimeter',
      'Generated via Chaos Game or Pascal mod 2'
    ],
    constructionSteps: [
      '1. Start with equilateral triangle.',
      '2. Connect midpoints of 3 edges.',
      '3. Remove central inverted triangle.',
      '4. Repeat recursively on 3 smaller triangles.'
    ],
    parametricEquations: 'f_1(x)=x/2, f_2(x)=x/2+(1/2,0), f_3(x)=x/2+(1/4, \\sqrt{3}/4)',
    visualizationSlug: 'sierpinski-triangle',
    hasExperiment: true,
    experimentSlug: 'fractal-lab',
    tags: ['Fractals', 'Geometry', 'Hausdorff Dimension', 'Chaos Game'],
    sources: ['Sierpiński, W. (1915)']
  },
  {
    id: 16,
    slug: 'koch-snowflake',
    title: 'Koch Snowflake',
    shortDescription: 'A continuous nowhere-differentiable fractal curve enclosing a finite area within an infinite perimeter.',
    fullDescription: 'Introduced by Helge von Koch in 1904. Starting with an equilateral triangle, each segment has its middle third replaced by a triangular tent.',
    categoryId: 8,
    status: 'PHENOMENON',
    intuition: 'An island of finite area surrounded by an infinite coastline! You can fence the entire snowflake with a small ring, but walking its edge takes infinite distance.',
    mathematics: 'Perimeter: P_n = 3s (4/3)^n -> infinity. Area: A_inf = 8/5 A_0. Dimension = log 4 / log 3 approx 1.262.',
    properties: [
      'Infinite perimeter',
      'Finite area = 8/5 A_0',
      'Continuous everywhere, differentiable nowhere',
      'Hausdorff dimension ~ 1.262'
    ],
    constructionSteps: [
      '1. Start with equilateral triangle.',
      '2. Divide each segment into 3 parts.',
      '3. Build equilateral tent on middle third.',
      '4. Repeat indefinitely.'
    ],
    parametricEquations: 'L_n = L_0 (4/3)^n',
    visualizationSlug: 'koch-snowflake',
    hasExperiment: true,
    experimentSlug: 'fractal-lab',
    tags: ['Fractals', 'Geometry', 'Infinite Perimeter'],
    sources: ['von Koch, H. (1904)']
  },
  {
    id: 17,
    slug: 'cantor-set',
    title: 'The Cantor Set (Cantor Dust)',
    shortDescription: 'A subset of the unit interval that is uncountably infinite, nowhere dense, and has measure zero.',
    fullDescription: 'Introduced by Georg Cantor in 1883. Repeatedly removing the open middle third leaves a dust of points that has the same cardinality as the real line yet zero length.',
    categoryId: 7,
    status: 'PHENOMENON',
    intuition: 'Remove 1/3, then 2/9, then 4/27... Total removed length equals exactly 1. Yet infinitely many points remain, uncountably many!',
    mathematics: 'Measure = 0. Cardinality |C| = 2^aleph_0. Hausdorff dimension = log 2 / log 3 approx 0.631.',
    properties: [
      'Measure zero',
      'Uncountable cardinality',
      'Totally disconnected and perfect set',
      'Hausdorff dimension ~ 0.631'
    ],
    constructionSteps: [
      '1. Start with [0, 1].',
      '2. Remove middle third (1/3, 2/3).',
      '3. Repeat on remaining intervals.',
      '4. Retains numbers with base-3 digits without 1.'
    ],
    parametricEquations: 'C = \\{ x = \\sum_{k=1}^\\infty a_k / 3^k : a_k \\in \\{0, 2\\} \\}',
    visualizationSlug: 'cantor-set',
    hasExperiment: true,
    experimentSlug: 'fractal-lab',
    tags: ['Set Theory', 'Analysis', 'Topology', 'Measure Zero'],
    sources: ['Cantor, Georg (1883)']
  },
  {
    id: 18,
    slug: 'dragon-curve',
    title: 'The Heighway Dragon Curve',
    shortDescription: 'A self-similar space-filling fractal curve generated by repeatedly folding a strip of paper in half.',
    fullDescription: 'Discovered in 1966 by Heighway, Banks, and Harter. Formed by repeatedly folding a paper strip in half, then unfolding each fold to a right angle.',
    categoryId: 8,
    status: 'PHENOMENON',
    intuition: 'Repeatedly folding paper and unfolding creases to 90 degrees produces a non-self-intersecting dragon curve that tiles the 2D plane perfectly.',
    mathematics: 'Boundary dimension approx 1.5236. Four dragon curves joined at origin tile R^2 without overlap.',
    properties: [
      'Paper-folding sequence of alternating turns',
      'Self-similar with 45-degree rotation scaling',
      'Tiles 2D plane seamlessly'
    ],
    constructionSteps: [
      '1. Fold strip of paper in half.',
      '2. Fold again in same direction.',
      '3. Unfold creases to 90 degrees.',
      '4. Observe fractal curve emerge.'
    ],
    parametricEquations: 'f_1(z) = \\frac{1+i}{2} z, \\quad f_2(z) = 1 - \\frac{1-i}{2} z',
    visualizationSlug: 'dragon-curve',
    hasExperiment: true,
    experimentSlug: 'fractal-lab',
    tags: ['Fractals', 'Paper Folding', 'Plane Tiling'],
    sources: ['Gardner, Martin (1967)']
  }
];

export const FALLBACK_TIMELINE: TimelineEvent[] = [
  { id: 1, year: 1637, dateDisplay: '1637', title: 'Fermat\'s Marginal Note', description: 'Pierre de Fermat scribbles his famous conjecture in the margin of Arithmetica.', significance: 'Drove the invention of algebraic number theory.', category: 'Number Theory', relatedProblemSlug: 'fermats-last-theorem' },
  { id: 2, year: 1742, dateDisplay: 'June 7, 1742', title: 'Goldbach\'s Letter to Euler', description: 'Christian Goldbach proposes every even integer > 2 is the sum of two primes.', significance: 'Initiated one of the most enduring open problems in additive number theory.', category: 'Number Theory', relatedProblemSlug: 'goldbach-conjecture' },
  { id: 3, year: 1858, dateDisplay: '1858', title: 'Discovery of the Möbius Strip', description: 'August Ferdinand Möbius and Johann Benedict Listing discover the first non-orientable surface.', significance: 'Founded the visual study of topology and orientation.', category: 'Topology', relatedWonderSlug: 'mobius-strip' },
  { id: 4, year: 1859, dateDisplay: '1859', title: 'Riemann\'s Landmark Paper', description: 'Bernhard Riemann formulates the Riemann Hypothesis connecting complex zeros of zeta to primes.', significance: 'The most celebrated open problem in pure mathematics.', category: 'Analysis', relatedProblemSlug: 'riemann-hypothesis' },
  { id: 5, year: 1882, dateDisplay: '1882', title: 'Felix Klein Conceives the Klein Bottle', description: 'Felix Klein describes a closed non-orientable surface with Euler characteristic 0.', significance: 'Expanded topology beyond physical 3-dimensional embeddings.', category: 'Topology', relatedWonderSlug: 'klein-bottle' },
  { id: 6, year: 1900, dateDisplay: 'August 8, 1900', title: 'Hilbert\'s 23 Problems', description: 'David Hilbert presents 23 unsolved problems at the ICM in Paris.', significance: 'Shaped mathematical research throughout the 20th century.', category: 'Foundations', relatedProblemSlug: 'riemann-hypothesis' },
  { id: 7, year: 1904, dateDisplay: '1904', title: 'Poincaré Conjecture Formulated', description: 'Henri Poincaré conjectures any simply connected closed 3-manifold is homeomorphic to the 3-sphere.', significance: 'Defined the frontier of 3-manifold topology.', category: 'Topology', relatedProblemSlug: 'poincare-conjecture' },
  { id: 8, year: 1931, dateDisplay: '1931', title: 'Gödel\'s Incompleteness Theorems', description: 'Kurt Gödel proves that any consistent formal system capable of basic arithmetic contains true statements that cannot be proved within the system.', significance: 'Established the limits of formal mathematical proof.', category: 'Logic', relatedProblemSlug: 'halting-problem' },
  { id: 9, year: 1936, dateDisplay: '1936', title: 'Turing and the Halting Problem', description: 'Alan Turing defines the Turing machine and proves the undecidability of the halting problem.', significance: 'Laid the foundation of theoretical computer science.', category: 'Computer Science', relatedProblemSlug: 'halting-problem' },
  { id: 10, year: 1963, dateDisplay: '1963', title: 'Independence of the Continuum Hypothesis', description: 'Paul Cohen invents forcing and proves that the Continuum Hypothesis cannot be proved from ZFC axioms.', significance: 'Demonstrated independence in modern set theory.', category: 'Logic', relatedProblemSlug: 'continuum-hypothesis' },
  { id: 11, year: 1971, dateDisplay: '1971', title: 'Cook-Levin Theorem: P vs NP', description: 'Cook and Levin independently formulate P vs NP and NP-completeness.', significance: 'The core question of computational efficiency.', category: 'Computer Science', relatedProblemSlug: 'p-vs-np' },
  { id: 12, year: 1994, dateDisplay: '1994', title: 'Fermat\'s Last Theorem Proved', description: 'Andrew Wiles completes his proof of Fermat\'s Last Theorem via modularity of elliptic curves.', significance: 'Triumphant resolution of a 350-year-old mystery.', category: 'Number Theory', relatedProblemSlug: 'fermats-last-theorem' },
  { id: 13, year: 2000, dateDisplay: 'May 24, 2000', title: 'Clay Millennium Prize Problems', description: 'Clay Mathematics Institute establishes seven $1,000,000 prize problems.', significance: 'The gold standard catalog of 21st century mathematics.', category: 'Foundations', relatedProblemSlug: 'riemann-hypothesis' },
  { id: 14, year: 2003, dateDisplay: '2002–2003', title: 'Perelman Proves Poincaré Conjecture', description: 'Grigori Perelman proves Thurston\'s Geometrization Conjecture and the Poincaré Conjecture with Ricci flow.', significance: 'The first Millennium Prize Problem resolved.', category: 'Topology', relatedProblemSlug: 'poincare-conjecture' },
  { id: 15, year: 2013, dateDisplay: '2013', title: 'Zhang & Maynard Bound Prime Gaps', description: 'Yitang Zhang and James Maynard prove bounded prime gaps unconditionally (< 246).', significance: 'Sensational breakthrough on the Twin Prime Conjecture.', category: 'Number Theory', relatedProblemSlug: 'twin-prime-conjecture' }
];

export const FALLBACK_VISUALIZATIONS: Visualization[] = [
  { id: 1, slug: 'mobius-strip', title: 'Interactive Möbius Strip Laboratory', description: 'Flagship 3D topological experience featuring step-by-step construction, surface tracing, boundary tracing, normal vector inversion, and parametric mathematics.', type: 'ThreeD', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 2, slug: 'klein-bottle', title: 'Klein Bottle 4D Immersion', description: 'Interactive 3D parametric figure-8 Klein bottle with cross-sectional slicing and non-orientability visualizer.', type: 'ThreeD', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 3, slug: 'torus', title: 'Parametric Torus & Topological Cycles', description: 'Interactive torus with adjustable major/minor radii, meridian and longitudinal geodesic paths, and cross-section slice.', type: 'ThreeD', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 4, slug: 'hyperbolic-geometry', title: 'Poincaré Disk Hyperbolic Plane', description: 'Interactive non-Euclidean geometry visualizer showing geodesics and parallel axiom failure.', type: 'Canvas2D', supportedModes: ['Explore', 'Guided'] },
  { id: 5, slug: 'hilberts-hotel', title: 'Hilbert\'s Hotel Interactive Simulator', description: 'Animated simulation of countable infinity: room shifts n -> n+1, +10, +100, and +infinity via n -> 2n.', type: 'InteractiveSim', supportedModes: ['Explore', 'Guided'] },
  { id: 6, slug: 'banach-tarski', title: 'Banach-Tarski Paradox Conceptualizer', description: 'Visual decomposition of a sphere into 5 non-measurable pieces and SO(3) rotation assembly.', type: 'ThreeD', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 7, slug: 'fractal-lab', title: 'Fractal Laboratory (Mandelbrot, Julia & IFS)', description: 'Interactive GPU/Canvas fractal explorer with dynamic zoom, pan, iteration depth, and Julia set parameter explorer.', type: 'Canvas2D', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 8, slug: 'collatz-conjecture', title: 'Collatz Trajectory Explorer', description: 'Interactive 3n+1 sequence plotter with stopping time, maximum excursion, and multi-number comparison.', type: 'InteractiveSvg', supportedModes: ['Explore', 'Guided'] },
  { id: 9, slug: 'goldbach-conjecture', title: 'Goldbach Decomposition Lab', description: 'Interactive even integer decomposition calculator with prime pair distribution and Goldbach comet.', type: 'InteractiveSvg', supportedModes: ['Explore', 'Guided'] },
  { id: 10, slug: 'twin-prime-conjecture', title: 'Twin Prime Sieve Explorer', description: 'Interactive prime number line highlighting (p, p+2) pairs and prime gap density.', type: 'InteractiveSvg', supportedModes: ['Explore', 'Guided'] },
  { id: 11, slug: 'riemann-hypothesis', title: 'Riemann Zeta Zero Spectrum', description: 'Complex plane visualizer with critical strip, critical line Re(s) = 1/2, and known non-trivial zeros.', type: 'Canvas2D', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 12, slug: 'zenos-paradoxes', title: 'Zeno\'s Paradoxes Interactive Laboratory', description: 'Achilles & Tortoise animated race, Dichotomy geometric series bar convergence, and Arrow instantaneous velocity limit.', type: 'InteractiveSim', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 13, slug: 'projective-plane', title: 'Real Projective Plane (Cross-Cap) 3D', description: 'Interactive 3D parametric cross-cap model of RP^2 illustrating antipodal quotient and non-orientability.', type: 'ThreeD', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 14, slug: 'cantors-diagonal-argument', title: 'Cantor\'s Diagonal Argument Visualizer', description: 'Interactive binary sequence table demonstrating diagonal bit inversion and uncountability of reals.', type: 'InteractiveSim', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 15, slug: 'birthday-paradox', title: 'Birthday Paradox Simulator & Calculator', description: 'Interactive room size slider, exact collision probability curve, and Monte Carlo multi-trial generator.', type: 'InteractiveSim', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 16, slug: 'monty-hall-problem', title: 'Monty Hall 3-Door Simulation & Monte Carlo', description: 'Interactive 3-door game showing switch vs stay strategies with live frequentist convergence.', type: 'InteractiveSim', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 17, slug: 'gabriels-horn', title: 'Gabriel\'s Horn 3D Surface of Revolution', description: 'Interactive 3D horn y = 1/x demonstrating finite volume versus infinite surface area.', type: 'ThreeD', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 18, slug: 'p-vs-np', title: 'P vs NP Verification vs Search Complexity Lab', description: 'Interactive complexity class visualizer and verification vs search demonstrator.', type: 'InteractiveSim', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 19, slug: 'poincare-conjecture', title: 'Poincaré Conjecture 3-Sphere Surgery Visualizer', description: 'Ricci flow neckpinch singularity surgery and simply connected loop shrinking visualizer.', type: 'ThreeD', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 20, slug: 'julia-set', title: 'Julia Sets Complex Plane Dynamics', description: 'Interactive Julia set fractal with custom parameter explorer linked to the Mandelbrot plane.', type: 'Canvas2D', supportedModes: ['Explore', 'Guided', 'Mathematical'] },
  { id: 21, slug: 'sierpinski-triangle', title: 'Sierpiński Triangle Recursive IFS', description: 'Recursive removal and chaos game generation of the Sierpiński gasket.', type: 'Canvas2D', supportedModes: ['Explore', 'Guided'] },
  { id: 22, slug: 'koch-snowflake', title: 'Koch Snowflake Infinite Shoreline', description: 'Iterative line replacement visualizer demonstrating infinite perimeter enclosing finite area.', type: 'Canvas2D', supportedModes: ['Explore', 'Guided'] },
  { id: 23, slug: 'cantor-set', title: 'Cantor Set Middle-Third Construction', description: 'Stage-by-stage removal of the middle third illustrating measure zero and uncountability.', type: 'Canvas2D', supportedModes: ['Explore', 'Guided'] },
  { id: 24, slug: 'dragon-curve', title: 'Heighway Dragon Paper-Folding Fractal', description: 'Recursive paper-folding turn generator and plane-tiling 2D fractal curve.', type: 'Canvas2D', supportedModes: ['Explore', 'Guided'] }
];
